DistanceED/urls.py
from django.contrib import admin
from django.urls import path, include  # Import include and path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myappF23/', include('myappF23.urls')),  # Include the URLs of myappF23
]

myappF23/urls.py
from django.urls import path
from . import views

app_name = 'myappF23'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<int:category_no>/', views.detail, name='detail'),
    path('instructor/<int:instructor_id>/', views.instructor_courses_students, name='instructor_courses_students'),

]

myappF23/models.py
# Submitted by:
# *--------------------*------------*
# | Krunali Sheth      | 110095010  |
# *--------------------*------------*
# | Srujan Oza         | 110100972  |
# *--------------------*------------*
# | Pratikraj Rajput   | 110097059  |
# *--------------------*------------*
# | Prem Goswami       | 110100984  |
# *--------------------*------------*

from django.db import models


# Create your models here.
class Student(models.Model):
    STUDENT_STATUS_CHOICES = [
        ("ER", "Enrolled"),
        ("SP", "Suspended"),
        ("GD", "Graduated"),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=True, default=None)
    date_of_birth = models.DateField()
    status = models.CharField(
        max_length=10, choices=STUDENT_STATUS_CHOICES, default="ER"
    )

    def __str__(self):
        return self.first_name + " " + self.last_name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Instructor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField()
    student = models.ManyToManyField(Student)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Course(models.Model):
    LEVEL_CHOICES = [
        ("BE", "Beginner"),
        ("IN", "Intermediate"),
        ("AD", "Advanced"),
    ]
    title = models.CharField(max_length=200)
    description = models.TextField()
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, default=None)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    students = models.ManyToManyField(Student, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    level = models.CharField(max_length=10, choices=LEVEL_CHOICES, default="BE")

    def __str__(self):
        return self.title

class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        (0, 'Order Confirmed'),
        (1, 'Order Cancelled'),
    ]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=1)
    order_date = models.DateField(auto_now=True)

    def __str__(self):
        return f"Order for {self.student} - {self.course}"

myappF23/views.py
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponse
from .models import Category, Course, Instructor


def index(request):
    category_list = Category.objects.all().order_by('id')[:10]
    course_list = Course.objects.all().order_by('-price')[:5]
    professor_list = Instructor.objects.all().order_by('last_name')
    context = {
        'category_list': category_list,
        'course_list': course_list,
        'professor_list': professor_list,
    }
    return render(request, 'myappF23/index.html', context)


def about(request):
    return render(request, 'myappF23/about.html')


def detail(request, category_no):
    category = get_object_or_404(Category, pk=category_no)
    course_list = Course.objects.filter(categories=category)
    return render(request, 'myappF23/detail.html', {'category': category, 'course_list': course_list})


def instructor_courses_students(request, instructor_id):
    instructor = get_object_or_404(Instructor, pk=instructor_id)
    courses = Course.objects.filter(instructor=instructor)

    context = {
        'instructor': instructor,
        'courses': courses,
    }
    return render(request, 'myappF23/instructor_detail.html', context)

templates/myappF23/about.html
{% extends 'myappF23/base.html' %}

{% block myhdg %}
    Hello Krunali
{% endblock %}

{% block title %}
About Us
{% endblock %}

{% block body_block %}
    <h2>About Us</h2>
    <p>This is a Distance Education Website! Search our Categories to find all available Courses.</p>
{% endblock %}

templates/myappF23/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us</title>
</head>
<body>
    <h1>About Us</h1>
    <p>This is a Distance Education Website! Search our Categories to find all available Courses.</p>
    <p><a href="{% url 'myappF23:index' %}">Back to Home</a></p>
</body>
</html>

templates/myappF23/base.html
<!DOCTYPE html>
{% load static %}
<html lang="">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myappF23/style.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div>
    <h1 id="greeting">{% block myhdg %}Hello User {% endblock %}</h1>
    {% block body_block %}*** {% endblock %}
</div>
<hr/>
<div>
    <ul>
        <li class="hbar1"><a href="/myappF23/about/">Find out about our ELearning site</a></li>
        <li class="hbar1"><a href="{% url 'myappF23:index' %}">Click here
            to return to main page</a><br/></li>
    </ul>
</div>
</body>
</html>

templates/myappF23/detail.html
{% extends 'myappF23/base.html' %}


{% block myhdg %}
    Hello Krunali
{% endblock %}

{% block title %}
{{ category.name }}
{% endblock %}

{% block body_block %}
    <h1>{{ category.name }}</h1>
    <ul>
        {% for course in course_list %}
            <li>{{ course.title }}</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/myappF23/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ category.name }}</title>
</head>
<body>
    <h1>{{ category.name }}</h1>
    <ul>
        {% for course in course_list %}
            <li>{{ course.title }}</li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'myappF23:index' %}">Back to Home</a></p>
</body>
</html>

templates/myappF23/index.html
{% extends 'myappF23/base.html' %}

{% block myhdg %}
    Hello Krunali
{% endblock %}

{% block body_block %}
    <div class="categories">
        {% if category_list %}
            <h2>List of Categories</h2>
            <ol>
                {% for category in category_list %}
                    <li><a href="{% url 'myappF23:detail' category.id %}">{{ category.name }}</a></li>
                {% endfor %}
            </ol>
        {% else %}
            <strong>There are no available categories!</strong>
        {% endif %}
    </div>

    <div class="professors">
        {% if professor_list %}
            <h2>List of Professors</h2>
            <ol>
                {% for professor in professor_list %}
                    <!-- Assuming the URL name for professor detail is 'myappF23:professor_detail' -->
                    <li><a href="{% url 'myappF23:instructor_courses_students' professor.id %}">{{ professor.first_name }} {{ professor.last_name }}</a></li>
                {% endfor %}
            </ol>
        {% else %}
            <strong>There are no available professors!</strong>
        {% endif %}
    </div>
{% endblock %}

templates/myappF23/index0.html
<!DOCTYPE html>
<html lang="">
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if category_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for category in category_list %}
        <li><a href="{% url 'myappF23:detail' category.id %}">{{ category.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href="{% url 'myappF23:about' %}">About page</a></p>
</body>
</html>

templates/myappF23/instructor_detail.html
{% extends 'myappF23/base.html' %}

{% block myhdg %}
    Hello Krunali
{% endblock %}

{% block title %}
{{ instructor.first_name }} {{ instructor.last_name }}
{% endblock %}

{% block body_block %}
    <h1>{{ instructor.first_name }} {{ instructor.last_name }}</h1>
    <p>{{ instructor.bio }}</p>
    <h2>Courses Taught</h2>
    <ul>
        {% for course in courses %}
            <li>{{ course.title }}</li>
        {% endfor %}
    </ul>


{% endblock %}